input_mode=rtmp
input=rtmp://127.0.0.1:1935/live/browser
input_args=-fflags nobuffer -analyzeduration 0 -probesize 32
ffmpeg=ffmpeg
mode=live-hls
overwrite=true
cpu_limit=50%
hls_segment_time=1
hls_list_size=3
hls_delete_segments=true
hls_append_list=false
hls_master_playlist=./out/live/master.m3u8
outputs=./profiles/live-hls-360p.conf,./profiles/live-hls-720p.conf,./profiles/live-hls-1080p.conf
